In [3]:
import pandas as pd

In [30]:
df = pd.read_csv('data_7000.csv')

In [11]:
import tensorflow as tf
from tensorflow.keras import layers


In [31]:
data = df.values

In [32]:
data = data[:,4:]

In [34]:
train_data = data[:,:-1]

In [37]:
labels = data[:,-1]

In [29]:
data

array([[279, 185, 0, ..., 0.0, 0.0, 0.0],
       [278, 438, 0, ..., 0.0, 0.0, 0.0],
       [278, 715, 0, ..., 0.0, 0.0, 0.0],
       ...,
       [270, 7321, 0, ..., 0.01, 0.01, 0.0],
       [220, 456, 0, ..., 0.0, 0.01, 0.0],
       [148, 4049, 0, ..., 0.0, 0.01, 0.0]], dtype=object)

In [40]:
import numpy as np

In [43]:
fr = pd.DataFrame(labels)

In [56]:
c=0
new = []
for i in labels:
    try:
        new.append(int(i))
    except:
        new.append(0)
        c+=1

In [57]:
len(new)

6999

In [58]:
c

169

In [61]:
Y = np.array (new)

In [62]:
Y

array([1, 1, 1, ..., 1, 1, 1])

In [63]:
Y

array([1, 1, 1, ..., 1, 1, 1])

In [65]:
train_data.shape
Y

array([1, 1, 1, ..., 1, 1, 1])

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
X_train,X_test,Y_train,Y_test = train_test_split(train_data,Y)

In [70]:
X_train.shape

(5249, 37)

In [73]:
X_test.shape

(1750, 37)

In [74]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

In [75]:
Y_train = to_categorical(Y_train,num_classes=2)
Y_test = to_categorical(Y_test,num_classes=2)

In [78]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential

In [102]:
model = Sequential()

In [103]:
model.add(Dense(30,activation='relu',input_shape=(37,)))
model.add(Dense(30,activation='relu'))

model.add(Dense(2,activation='softmax'))

In [104]:
model.compile(loss='categorical_crossentropy',metrics=['acc'],optimizer='adam')

In [105]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 30)                1140      
_________________________________________________________________
dense_13 (Dense)             (None, 30)                930       
_________________________________________________________________
dense_14 (Dense)             (None, 2)                 62        
Total params: 2,132
Trainable params: 2,132
Non-trainable params: 0
_________________________________________________________________


In [106]:
model.fit(X_train,Y_train,epochs=10)

Epoch 1/10
5249/5249 [==============================] - 0s 92us/sample - loss: 3.5195 - acc: 0.9291
Epoch 2/10
5249/5249 [==============================] - 0s 56us/sample - loss: 0.0569 - acc: 0.9895
Epoch 3/10
5249/5249 [==============================] - 0s 56us/sample - loss: 0.0159 - acc: 0.9943
Epoch 4/10
5249/5249 [==============================] - 0s 55us/sample - loss: 0.0095 - acc: 0.9962
Epoch 5/10
5249/5249 [==============================] - 0s 54us/sample - loss: 0.0109 - acc: 0.9968
Epoch 6/10
5249/5249 [==============================] - 0s 53us/sample - loss: 0.0131 - acc: 0.9973
Epoch 7/10
5249/5249 [==============================] - 0s 56us/sample - loss: 0.0069 - acc: 0.9981
Epoch 8/10
5249/5249 [==============================] - 0s 57us/sample - loss: 0.0177 - acc: 0.9956
Epoch 9/10
5249/5249 [==============================] - 0s 56us/sample - loss: 0.0157 - acc: 0.9971
Epoch 10/10
5249/5249 [==============================] - 0s 56us/sample - loss: 0.0248 - acc: 0.9962

In [107]:
model.evaluate(X_test,Y_test)

1750/1750 [==============================] - 0s 64us/sample - loss: 0.0042 - acc: 0.9977


[0.004163886171399867, 0.9977143]